version: '3.7'
services:
  php:
    build:
      context: ./var/docker/php7-fpm
    ports:
      - "9000:9001"
    volumes:
      - .:/var/www/symfony:cached
  nginx:
    build: ./var/docker/nginx
    ports:
      - 80:80
    links:
      - php
    volumes:
      - .:/var/www/symfony:cached
